version: '3.8'

services:
  secureshield-app:
    build: .
    image: secureshield-app:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/secureshield
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - app-uploads:/usr/src/app/server/uploads
    networks:
      - secureshield-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - secureshield-network
    restart: unless-stopped

volumes:
  dbdata:
  app-uploads:

networks:
  secureshield-network:
    driver: bridge
